import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const addCastToDB = api.verify.verifyCast.useMutation();
  const handleSubmit = async () => {
    addCastToDB.mutate({
      twitterHandle: '_yashkarthik',
      fName: 'yashkarthik',
      castLink: 'farcaster://casts/0x282591aadcef882bfc93a81879d86e10efc1f7d324a4c9b1dd1f4c676be5f61b/0x282591aadcef882bfc93a81879d86e10efc1f7d324a4c9b1dd1f4c676be5f61b'
    });
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <button onClick={() => handleSubmit()} className="border-2 border-solid border-white text-white">
              Tweet console.log button
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
